export const SET_MCKS = 'SET_MCKS'
export const GET_MCK = 'GET_MCK'
export const SET_USER_LOGGED_IN = 'SET_USER_LOGGED_IN'
export const SET_MARKERS = 'SET_MARKERS'
export const SEARCH_MCKS = 'SEARCH_MCKS'
